Repository Opensourcecontri/Hacktoberfest-2021, pull requests merged in 2021-10, with the labels that each got.

#1 Create Most Stones Removed with Same Row or Column.py
  python/Most Stones Removed with Same Row or Column.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#4 Create N-Repeated Element in Size 2N Array.py
  python/N-Repeated Element in Size 2N Array.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest

#2 Create Savedwifipasswordfinder.py
  python/Savedwifipasswordfinder.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#3 Added push ups Counter in Python Language
  python/pushupsCounter.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#5 added lcs code
  LCS.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#6 Create Binary Search Tree to Greater Sum Tree.py
  python/Binary Search Tree to Greater Sum Tree.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#7 Create Maximum Depth of Binary Tree.py
  python/Maximum Depth of Binary Tree.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#8 Create Container With Most Water.py
  python/Container With Most Water.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#11 Create Pairs of Songs With Total Durations Divisible by 60.py
  python/Pairs of Songs With Total Durations Divisible by 60.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#10 Create Maximum Nesting Depth of Two Valid Parentheses Strings.py
  python/Maximum Nesting Depth of Two Valid Parentheses Strings.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#9 Create Binary Tree Zigzag Level Order Traversal.py
  python/Binary Tree Zigzag Level Order Traversal.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#13 Create Count Good Nodes in Binary Tree.py
  python/Count Good Nodes in Binary Tree.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#12 Create Symmetric Tree.py
  python/Symmetric Tree.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#17 Sudoku Solver C++
  Sudoku Solver
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#16 Indian Coin Exchange in C++
  Indian Coin Exchange
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#15 Add Sum_of_Nodes.cpp
  Sum_of_Nodes.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#14 create a rock paper scissors game and add it
  python/rock-paper-scissors-game.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#24 PigGame in java script
  javascript/script.js
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#23 Rat in Maze - C++
  cpp/Rat in Maze
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#22 N-Queen problem - C++
  cpp/N-Queen
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#25 Guess my number game using java script
  javascript/index.js
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#19 read and displays emails
  python/readEmail.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#21 LCS for 3 Strings - C++
  cpp/LCS for 3 Strings
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#26 Create selectionsort.py
  selectionsort.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#18 Create AIAssistant.py
  python/AIAssistant.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#27 created WordWrapProblem.py
  python/WordWrapProblem.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#28 The 3sum problem solution is uploaded
  3sum.py
  python/3sum.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#29 Tic Tac Toe
  python/tictactoe.py
Labels: hacktoberfest-accepted, hacktober-fest, Hacktoberfest

#30 Added cpp programs for queue operations
  cpp/Deque-Implementation/Deque-Implementation
  cpp/Deque-Implementation/Deque-Implementation.cpp
  cpp/Deque-Implementation/Explanation.md
  cpp/Generating-Binary-Numbers/Explanation.md
  cpp/Generating-Binary-Numbers/Generating-Binary-Numbers-Using-Queue
  cpp/Generating-Binary-Numbers/Generating-Binary-Numbers-Using-Queue.cpp
  cpp/LRUQ/Explanation.md
  cpp/LRUQ/Least-Recently-Used-Queue
  cpp/LRUQ/Least-Recently-Used-Queue.cpp
  cpp/Queue_push&pop/queue-push-and-pop
  cpp/Queue_push&pop/queue-push-and-pop.cpp
  cpp/Reverse-First-K-element-Queue/DG
  cpp/Reverse-First-K-element-Queue/Explnantion.md
  cpp/Reverse-First-K-element-Queue/reverse-1st-k-element-queue
  cpp/Reverse-First-K-element-Queue/reverse-1st-k-element-queue.cpp
  cpp/Sliding-Window-Maximum/sliding-window-max-deque
  cpp/Sliding-Window-Maximum/sliding-window-max-deque.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#31 Internet Speed Test - GUI
  python/Internet Speed Test - GUI
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#32 Matrix_Multiplication.cpp
  cpp/Matrix_Multiplication.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#35 add bubble sort algorithm in cpp
  cpp/bubble_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#38 Tower of Hanoi.cpp
  cpp/Tower of Hanoi using DP - Cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#37 Floyd Warshall.cpp
  cpp/Floyd Warshall CPP
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#34 Permutations of String.cpp
  cpp/Find Permutations of String using Backtracking
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#20 Updated python folder with spotify data extraction notebook
  python/Spotifydataextraction.ipynb
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#42 add is palindrom number checker algorithm in go
  go/ispalindrom.go
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#44 Create Convert Sorted Array to Binary Search Tree.py
  python/Convert Sorted Array to Binary Search Tree.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#41 Added Double LinkedList in Python
  cpp/DictionarySort.cpp
  python/DoubleLinkedList.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#45 Solve the 3sum problem using Java
  java/threeSumProblem.java
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#48 Create Stream.cpp
  cpp/Stream.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#52 Create Construct Binary Tree from Preorder and Inorder Traversal.py
  python/Construct Binary Tree from Preorder and Inorder Traversal.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#53 Create Defanging an IP Address.py
  python/Defanging an IP Address.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#54 Create Replace Elements with Greatest Element on Right Side.py
  python/Replace Elements with Greatest Element on Right Side.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#50 Create ZigZag.py
  python/ZigZag.py
Labels: hacktoberfest-accepted, hacktober-fest, Hacktoberfest

#55 Create numcheck.py
  python/numcheck.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#40 Create linearsearch
  python/linear_search.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#57 Create Decompress Run-Length Encoded List.py
  python/Decompress Run-Length Encoded List.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#56 ArrayList program using java uploaded
  java/arrayList.java
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#58 Delete A node from a linked List
  python/delete_a_node.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#43 Dakshjain1
  python/hourGlassStarPattern.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#63 Fibonacci using Dynamic Programming Java
  java/fibonacci.java
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#62 Added Vectors_implementation
  cpp/Vectors_implementation.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#60 Adding Binary Search in java
  java/BinarySearch.java
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#61 Create pattern_inverted.cpp
  cpp/pattern_inverted.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#51 generate random portraits
  html/portraits.html
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#64 Random Forest Regression
  python/Random forest Regression/Position_Salaries.csv
  python/Random forest Regression/Untitled.ipynb
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#66 Adding python youtube-gui
  python/Youtube-Gui-Video-Downloader.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#65 Create factorial.cpp
  cpp/factorial.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#59 adding a guessing game
  python/Guessing_game(hard).py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#68 Create Stone-paper-scissor-game.py
  python/Stone-paper-scissor-game.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#69 Create merge linked lists
  python/mergelist.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#71 reverse linked list in python
  python/reverselinkedlist.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#72 Tkinter
  python/Desktop-tools-tkinter/hand-gesture-volume/assets/clip1-min_34.png
  python/Desktop-tools-tkinter/hand-gesture-volume/assets/icons8-audio-64.png
  python/Desktop-tools-tkinter/hand-gesture-volume/assets/icons8-low-volume-64.png
  python/Desktop-tools-tkinter/hand-gesture-volume/assets/icons8-microphone-100.png
  python/Desktop-tools-tkinter/hand-gesture-volume/assets/icons8-microphone-50.png
  python/Desktop-tools-tkinter/hand-gesture-volume/assets/icons8-microphone-64.png
  python/Desktop-tools-tkinter/hand-gesture-volume/assets/icons8-no-audio-64.png
  python/Desktop-tools-tkinter/hand-gesture-volume/assets/icons8-stretch-tool-64.png
  python/Desktop-tools-tkinter/hand-gesture-volume/hand.py
  python/Desktop-tools-tkinter/hand-gesture-volume/main.py
  python/Desktop-tools-tkinter/hand-gesture-volume/main.spec
  python/Desktop-tools-tkinter/hand-gesture-volume/pywhatkit_dbs.txt
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#73 Added CombSort.java
  java/CombSortingAlgo.java
Labels: hacktoberfest-accepted, Hacktoberfest

#74 eliminate.py
  python/eliminate.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#75 Added Chatbot!
  python/chatbot.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#76 Adding two files program in C++
  cpp/Google KickStart 2020 Round H - Retype.cpp
  cpp/caesarCipher.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#77 Adding files to Python Folder
  python/factorial.py
  python/prime.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#78 Added Keylogger Program
  python/keylogger.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#79 SplitArray.py
  python/SplitArray.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#80 Python user login system
  python/Python User Login system(TechnoFrost27).py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#82 Create 8-queens.py
  python/8-queens.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#83 Added password generator
  python/Password Generator(TechnoFrost27).py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#84 Add Fizzbuzz in python
  python/fizzbuzz.py
Labels: hacktoberfest-accepted

#85 Added breadth first search algorithm
  java/BFS.java
Labels: hacktoberfest-accepted

#87 Added NameGenerator.py
  python/NameGenerator.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#94 Create Traveling-Salesman Problem.py
  python/Traveling-Salesman Problem.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#93 Add files via upload
  cpp/DDA.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#92 add bubblesort java
  java/BubbleSort.java
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#91 program to solve sudoku
  python/sudoku.py
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#89 Find Unique.java
  java/Find Unique.java
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#88 Stock price prediction using ML project
  python/Stock_Price_Prediction_using_LSTM.ipynb
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktober-fest, Hacktoberfest

#95 Add complex numbers using Structures in CPP
  cpp/add_complex_using_struc.cpp
Labels: hacktoberfest-accepted

#96 Create quizgame.py
  quizgame.py
Labels: hacktoberfest-accepted

#97 Create ponggame.py
  ponggame.py
Labels: hacktoberfest-accepted

#98 Create Hungry snake game.py
  Hungry snake game.py
Labels: hacktoberfest-accepted

#99 Create grouping.py
  grouping.py
Labels: hacktoberfest-accepted

#100 Array Problems
  python/KadaneAlgo.py
  python/KthSmallestElement.py
Labels: hacktoberfest-accepted

#101 factorial of a number with different time complexities
  cpp/factorial_dp.cpp
Labels: hacktoberfest-accepted

#102 Beautiful Path in Array
  python/BeautifulPath.py
Labels: hacktoberfest-accepted

#104 graph implementation
  cpp/graphImplementation.cpp
Labels: hacktoberfest-accepted

#105 Create combining.py
  combining.py
Labels: hacktoberfest-accepted

#106 wine problem of dp
  cpp/wineProblemDP.cpp
Labels: hacktoberfest-accepted

#107 maxProfit dp problem
  cpp/maxProfitDP.cpp
Labels: hacktoberfest-accepted

#108 Added Depth First Search
  java/DFS.java
Labels: hacktoberfest-accepted

#109 Create merge_sort.cpp
  cpp/merge_sort.cpp
Labels: hacktoberfest-accepted

#110 Create Generate multiple table.cpp
  Generate multiple table.cpp
Labels: hacktoberfest-accepted

#111 Revert "Create condition.py"
  condition.py
Labels: hacktoberfest-accepted

#113 0-1 Knapsack Problem
  cpp/knapsack.cpp
Labels: hacktoberfest-accepted

#114 Add Ahorcado Game program and Lexicon.txt file
  python/ahorcadoGame/Ahorcado Game.py
  python/ahorcadoGame/Lexicon.txt
Labels: hacktoberfest-accepted

#115 Dijikstra Shortest path algorithm
  cpp/dijikstra.cpp
Labels: hacktoberfest-accepted

#116 Rock paper scissors in JS
  javascript/rock-paper-scissors/index.html
  javascript/rock-paper-scissors/main.js
Labels: hacktoberfest-accepted

#117 Created factorial.java
  java/factorial.java
Labels: hacktoberfest-accepted

#118 Calculator.html
  html/Calculator.html
Labels: hacktoberfest-accepted

#119 Quizz-web-app
  python/Flask/Quizz-App/README.md
  python/Flask/Quizz-App/app.py
  python/Flask/Quizz-App/main.py
  python/Flask/Quizz-App/static/good.gif
  python/Flask/Quizz-App/static/style.css
  python/Flask/Quizz-App/templates/index.html
  python/Flask/Quizz-App/templates/scoreboard.html
Labels: hacktoberfest-accepted

#120 TIC_TAC_TOE_GAME.CPP
  tic_tac_toe_game.cpp
Labels: hacktoberfest-accepted

#121 Create Next_Permutation
  java/Next_Permutation
Labels: hacktoberfest-accepted

#122 Add brick breaker game in JavaScript folder
  javascript/brickBreakerGame/index.css
  javascript/brickBreakerGame/index.html
  javascript/brickBreakerGame/index.js
Labels: hacktoberfest-accepted

#123 Create insertionsort.cpp
  insertionsort.cpp
Labels: hacktoberfest-accepted

#124 Add Arduino Simple Struct
  arduino/simpleArduinoStruct/simpleArduinoStruct.ino
Labels: hacktoberfest-accepted

#125 Round Robin Scheduling #hacktoberfest
  cpp/RoundRobin.cpp
Labels: hacktoberfest-accepted

#126 Added Bit Manipulation program in C++
  cpp/Bit Manipulation/bit_manipulation.cpp
Labels: hacktoberfest-accepted

#127 Create Main.js
  javascript/Main.js
Labels: hacktoberfest-accepted

#128 Create app.js
  javascript/app.js
Labels: hacktoberfest-accepted

#129 Create Kadane.cpp
  cpp/Kadane.cpp
Labels: hacktoberfest-accepted

#130 Create MoveNegativesOneSide.cpp
  cpp/MoveNegativesOneSide.cpp
Labels: hacktoberfest-accepted

#131 InnocentDaksh63/armstrong.c
  InnocentDaksh63
Labels: hacktoberfest-accepted

#132 Revert "InnocentDaksh63/armstrong.c"
  InnocentDaksh63
Labels: invalid

#133 Disjoint set union cpp
  cpp/DSU.cpp
Labels: hacktoberfest-accepted

#134 Sieve of eratosthenes code for CPP added.
  cpp/sieve _of_eratosthenes.cpp
Labels: hacktoberfest-accepted

#136 Added reverse k node alternatively in linked list.
  reverse_k_nodes_alternatively.cpp
Labels: hacktoberfest-accepted

#137 Practice Problems in C Language
  C-Language/Alphabatical order of string.c
  C-Language/BFS.c
  C-Language/BST.c
  C-Language/DFS.c
  C-Language/FCFS.c
  C-Language/LFU page replacement algo.c
  C-Language/LRU page replacement algo.c
  C-Language/Round robin.c
  C-Language/SJF.c
  C-Language/Smallest among two numbers.c
  C-Language/alphabatical oder of names.c
  C-Language/arrange array in inc. & dec. order.c
  C-Language/arrange array in inc. and dec. order.c
  C-Language/array.c
  C-Language/ascending order of an array.c
  C-Language/bankers algorithm for deadlock avoidance.c
  C-Language/c++.c
  C-Language/c-scan disk scheduling algo.c
  C-Language/calculate sum of series of n numbers.c
  C-Language/complexity insertion sort.c
  C-Language/complexity quick sort.c
  C-Language/dijkstra algorithm.c
  C-Language/dijkstra.c
  C-Language/dinning philospher problem.c
  C-Language/entering the pointer.c
  C-Language/fcfs for disk scheduling algo.c
  C-Language/fifo page replacement algo.c
  C-Language/finding largest and smallest numbers.c
  C-Language/finding largest element in data array.c
  C-Language/increasing order of an array.c
  C-Language/insertion sort.c
  C-Language/knapsack problem.c
  C-Language/knapsack.c
  C-Language/kruskal algorithm.c
  C-Language/largest and smallest among two nos..c
  C-Language/largest element in data array.c
  C-Language/largest element.c
  C-Language/largest number among them.c
  C-Language/merge sort.c
  C-Language/optimal binary search tree.c
  C-Language/optimal page replacement algo.c
  C-Language/pagging technique for memory management.c
  C-Language/prims algorithm.c
  C-Language/print a to z.c
  C-Language/printing character from a to z.c
  C-Language/priorty cpu schedulingalgo.c
  C-Language/producer consumer problem.c
  C-Language/program for FCFS.c
  C-Language/quick sort.c
  C-Language/scan disk scheduling algo.c
  C-Language/sum of series of numbers.c
  C-Language/time complexity of insertion sort.c
Labels: hacktoberfest-accepted

#140 Create Dictionary sum
  python/Dictionary sum
Labels: hacktoberfest-accepted

#141 Maximum and Minimum
  python/Maximum and Minimum
Labels: hacktoberfest-accepted

#142 Palindrome number
  java/PalindromeNumber.java
Labels: hacktoberfest-accepted

#143 Create ALS.cpp
  ALS.cpp
Labels: hacktoberfest-accepted

#144 Create rabin_carp.cpp
  rabin_carp.cpp
Labels: hacktoberfest-accepted

#145 Create KMP.cpp
  KMP.cpp
Labels: hacktoberfest-accepted

#146 Create FloodFill.cpp
  FloodFill.cpp
Labels: hacktoberfest-accepted

#147 subset_sum.cpp
  cpp/subset_sum.cpp
Labels: hacktoberfest-accepted

#149 Create PersistentTree.java
  PersistentTree.java
Labels: hacktoberfest-accepted

#151 Create Floyd_Warshall.cpp
  Floyd_Warshall.cpp
Labels: hacktoberfest-accepted

#153 Nodemailer app created
  node-emailSender/app.js
  node-emailSender/node_modules/nodemailer/.prettierrc.js
  node-emailSender/node_modules/nodemailer/CHANGELOG.md
  node-emailSender/node_modules/nodemailer/CODE_OF_CONDUCT.md
  node-emailSender/node_modules/nodemailer/CONTRIBUTING.md
  node-emailSender/node_modules/nodemailer/LICENSE
  node-emailSender/node_modules/nodemailer/README.md
  node-emailSender/node_modules/nodemailer/SECURITY.txt
  node-emailSender/node_modules/nodemailer/lib/addressparser/index.js
  node-emailSender/node_modules/nodemailer/lib/base64/index.js
  node-emailSender/node_modules/nodemailer/lib/dkim/index.js
  node-emailSender/node_modules/nodemailer/lib/dkim/message-parser.js
  node-emailSender/node_modules/nodemailer/lib/dkim/relaxed-body.js
  node-emailSender/node_modules/nodemailer/lib/dkim/sign.js
  node-emailSender/node_modules/nodemailer/lib/fetch/cookies.js
  node-emailSender/node_modules/nodemailer/lib/fetch/index.js
  node-emailSender/node_modules/nodemailer/lib/json-transport/index.js
  node-emailSender/node_modules/nodemailer/lib/mail-composer/index.js
  node-emailSender/node_modules/nodemailer/lib/mailer/index.js
  node-emailSender/node_modules/nodemailer/lib/mailer/mail-message.js
  node-emailSender/node_modules/nodemailer/lib/mime-funcs/index.js
  node-emailSender/node_modules/nodemailer/lib/mime-funcs/mime-types.js
  node-emailSender/node_modules/nodemailer/lib/mime-node/index.js
  node-emailSender/node_modules/nodemailer/lib/mime-node/last-newline.js
  node-emailSender/node_modules/nodemailer/lib/mime-node/le-unix.js
  node-emailSender/node_modules/nodemailer/lib/mime-node/le-windows.js
  node-emailSender/node_modules/nodemailer/lib/nodemailer.js
  node-emailSender/node_modules/nodemailer/lib/qp/index.js
  node-emailSender/node_modules/nodemailer/lib/sendmail-transport/index.js
  node-emailSender/node_modules/nodemailer/lib/ses-transport/index.js
  node-emailSender/node_modules/nodemailer/lib/shared/index.js
  node-emailSender/node_modules/nodemailer/lib/smtp-connection/data-stream.js
  node-emailSender/node_modules/nodemailer/lib/smtp-connection/http-proxy-client.js
  node-emailSender/node_modules/nodemailer/lib/smtp-connection/index.js
  node-emailSender/node_modules/nodemailer/lib/smtp-pool/index.js
  node-emailSender/node_modules/nodemailer/lib/smtp-pool/pool-resource.js
  node-emailSender/node_modules/nodemailer/lib/smtp-transport/index.js
  node-emailSender/node_modules/nodemailer/lib/stream-transport/index.js
  node-emailSender/node_modules/nodemailer/lib/well-known/index.js
  node-emailSender/node_modules/nodemailer/lib/well-known/services.json
  node-emailSender/node_modules/nodemailer/lib/xoauth2/index.js
  node-emailSender/node_modules/nodemailer/package.json
  node-emailSender/node_modules/nodemailer/postinstall.js
  node-emailSender/package-lock.json
  node-emailSender/package.json
Labels: hacktoberfest-accepted

#157 Palindrome string
  java/BinarySearch.java
  java/DFS.java
  java/Graph.java
  java/PalindromeNumber.java
  java/PalindromeString.java
  java/Solution.java
  java/factorial.java
Labels: hacktoberfest-accepted

#159 Hacktoberfest - ItalianCard
  java/italiandeck/ItalianCard.java
  java/italiandeck/ItalianDeck.java
Labels: hacktoberfest-accepted

#162 Is String Palindrome program added.
  cpp/is_string_palindrome.cpp
Labels: hacktoberfest-accepted

#163 Is Number Palindrome C++ program added.
  cpp/is_Number_Palindrome.cpp
Labels: hacktoberfest-accepted

#164 Powerof2.cpp
  cpp/Bit Manipulation/Powerof2.cpp
Labels: hacktoberfest-accepted

#165 AddStarAtRepeated
  cpp/AddStarAtRepeated
Labels: hacktoberfest-accepted

#168 Create removeXinString
  cpp/removeXinString
Labels: hacktoberfest-accepted

#169 added instagram-clone to Python-Projects
  Python-Projects/instagram-clone/__pycache__/app.cpython-38.pyc
  Python-Projects/instagram-clone/__pycache__/helpers.cpython-38.pyc
  Python-Projects/instagram-clone/__pycache__/routes.cpython-38.pyc
  Python-Projects/instagram-clone/animalgram.db
  Python-Projects/instagram-clone/app.py
  Python-Projects/instagram-clone/db.py
  Python-Projects/instagram-clone/helpers.py
  Python-Projects/instagram-clone/routes.py
  Python-Projects/instagram-clone/static/css/layout.css
  Python-Projects/instagram-clone/templates/apology.html
  Python-Projects/instagram-clone/templates/create_post.html
  Python-Projects/instagram-clone/templates/index.html
  Python-Projects/instagram-clone/templates/layout.html
  Python-Projects/instagram-clone/templates/login.html
  Python-Projects/instagram-clone/templates/register.html
Labels: hacktoberfest-accepted

#172 subsets.cpp
  cpp/Bit Manipulation/subsets.cpp
Labels: hacktoberfest-accepted

#173 Create selectionSort
  cpp/selectionSort
Labels: hacktoberfest-accepted

#175 Create hashmaps
  cpp/hashmaps
Labels: hacktoberfest-accepted

#176 Create quickSort
  cpp/quickSort
Labels: hacktoberfest-accepted

#177 twoRepeatingTwice.cpp
  cpp/Bit Manipulation/twoRepeatingTwice.cpp
Labels: hacktoberfest-accepted

#178 Added registration page made with html css
  Web-page/images/backImg.jpg
  Web-page/images/frontImg.jpg
  Web-page/registration.html
  Web-page/style.css
Labels: hacktoberfest-accepted

#179 added radix sort code using bin/bucket sort
  cpp/radixSort.cpp
Labels: hacktoberfest-accepted

#180 Added a insertion sort python file
  python/insertionsort.py
Labels: hacktoberfest-accepted
